---
- name: "Apache installation using docker container"
  hosts: prod
  become: true
  pre_tasks:
    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
      changed_when: false

    - name: Install docker python
      pip: name=docker-py 
  tasks:
  - name: Create a docker container
    docker_container:
      name: webapp
      image: httpd
      ports:
       - "80:80"
